name: Docker

on:
  workflow_dispatch: 
    inputs: 
      tag:
        description: "Tag"
        required: true
        

      
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
              
    - name: Docker login
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build & Push Image
      run: |
        docker buildx build --file Dockerfile --platform linux/amd64,linux/arm/v7,linux/arm64 --output "type=image,push=true" --tag leantime/leantime:${{ github.event.inputs.tag }} .
      
