name: Docker

on:
  workflow_dispatch: 
    inputs: 
      tag:
        description: "Tag"
        required: true
        

      
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
              
    - name: Docker login
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
       
    - name: Docker builder for amd
      run: |
          docker buildx use $(docker buildx create --platform linux/amd64)
         
    - name: Build & Push linux/amd64
      run: |
        docker buildx build --file Dockerfile --platform linux/amd64 --output "type=image,push=true" --tag leantime/leantime:${{ github.event.inputs.tag }} .
      
    - name: Docker builder for arm
      run: |
          docker buildx use $(docker buildx create --platform linux/arm64,linux/arm/v8)
         
    - name: Build & Push arm
      run: |
        docker buildx build --file Dockerfile --platform linux/arm/v8,linux/arm64 --output "type=image,push=true" --tag leantime/leantime:${{ github.event.inputs.tag }} .
