name: Docker

on:
  workflow_dispatch: 

      
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: latest
          
    - name: Docker login
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build image
      run: docker build . --file Dockerfile --tag leantime/leantime:latest
      
    - name: Docker Push
      run: docker push leantime/leantime
